<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body></body>
  <script>
    /*
        2. ¿Cal é a saída do seguinte código? ¿Por que?
    */

    function job() {
      return new Promise(function (resolve, reject) {
        reject();
      });
    }
    let promise = job();
    promise
      .then(() => console.log("Success 1"))
      .then(() => console.log("Success 2"))
      .then(() => console.log("Success 3"))
      .catch(() => console.log("Error 1"))
      .then(() => console.log("Success 4"));

    /*
        Saida:

        Error 1
        Success 4

        Ao ter un reject na liña 17 recollese o erro co catch na liña 25 despois do catch imprimese Success 4.

      */
  </script>
</html>
